# apiVersion: v1
# kind: Namespace
# metadata:
#   name: app-demo
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-frontend
  namespace: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo-frontend
  template:
    metadata:
      labels:
        app: app-demo-frontend
    spec:
      containers:
        - name: app-demo-frontend
          image: httpd
          resources:
            limits:
              memory: "256Mi"
              cpu: "128m"
          ports:
            - name: web
              containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-frontend-svc
  namespace: app-demo
  labels:
    app: app-demo-frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: app-demo-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-demo-frontend-ingress
  namespace: app-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: kispace.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-demo-frontend-svc
                port:
                  number: 80
